apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ops-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: RoarApp is the Schema for the roarapps API
      displayName: Roar App
      kind: RoarApp
      name: roarapps.roarapp.roarapp.com
      version: v1alpha1
  description: Ops operator
  displayName: ops-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ops-operator
  links:
  - name: Ops Operator
    url: https://ops-operator.domain
  maturity: alpha
  provider:
    name: provider ops
    url: url
  version: 0.0.0
