apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ops-opr-subscription
  namespace: mss-dev
spec:
  channel: alpha
  name: ops-operator
  source: ops-catalog
  sourceNamespace: mss-dev